theme: jekyll-theme-tactile
title: KB-74 Applied Data Science
description: Rapporteert over de voortgang van de projecten bij KB-74
show_downloads: False
google_analytics: UA-101965499-1
is_project_page: False
site.logo: _img/ITD_ENG_groen_JPG.jpg
